# 48. Rotate Image (Not transpose)
https://leetcode.com/problems/rotate-image/description/

**Note that the required rotation is not a traspose operation**

In [1]:
def rotation(matrix):
    # reverse
    l = 0
    r = len(matrix) -1
    while l < r:
        matrix[l], matrix[r] = matrix[r], matrix[l]
        l += 1
        r -= 1
    # transpose 
    for i in range(len(matrix)):
        for j in range(i):
            matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]

    return matrix


# Example usage:
original_matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print("Original Matrix:")
print(original_matrix)
print("\Rotated Matrix:")
print(rotation(original_matrix))


Original Matrix:
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
\Rotated Matrix:
[[7, 4, 1], [8, 5, 2], [9, 6, 3]]


In [3]:
def rotate(matrix):
    """
    Do not return anything, modify matrix in-place instead.
    """
    
    
    n = len(matrix)
    
    # iterate through matrix
    for i in range(n):
        for j in range(i,n): # range(i+1,n)
        
            # transpose the matrix, turning rows into columns and vice versa
            matrix[i][j],matrix[j][i] = matrix[j][i],matrix[i][j]
        
        # reverse the resulting rows
        matrix[i].reverse() # reverse row by row
    return matrix


# Example usage:
original_matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print("Original Matrix:")
print(original_matrix)
print("\Rotated Matrix:")
print(rotate(original_matrix))


Original Matrix:
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
\Rotated Matrix:
[[7, 4, 1], [8, 5, 2], [9, 6, 3]]


In [18]:
def transpose(matrix):

    
    n = len(matrix)
    # iterate through matrix
    for i in range(n):
        for j in range(i+1,n):
        
            # transpose the matrix, turning rows into columns and vice versa
            matrix[i][j],matrix[j][i] = matrix[j][i],matrix[i][j]
    return matrix


def rotate(matrix):
    matrix = transpose(matrix)

    # Reverse each row
    for i in range(len(matrix)):
        matrix[i].reverse()

    return matrix

# Example usage:
original_matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print("Original Matrix:")
print(original_matrix)
print("\Rotated Matrix:")
print(rotate(original_matrix))


Original Matrix:
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
\Rotated Matrix:
[[7, 4, 1], [8, 5, 2], [9, 6, 3]]


In [19]:
# Example usage:
original_matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]


print(list(reversed(original_matrix))) # Not In-place, Creating reversed copy

# Trying to assign the return value of .reverse() to a variable is a common mistake
print(original_matrix.reverse()) # In-place, .reverse() doesn’t return a new list but None

print(original_matrix) # reversed matrix


[[7, 8, 9], [4, 5, 6], [1, 2, 3]]
None
[[7, 8, 9], [4, 5, 6], [1, 2, 3]]


# Transpose

In [5]:
import numpy as np

# Your original matrix
original_matrix = np.array([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]])

# Transpose the matrix
transposed_matrix = np.transpose(original_matrix)

# Alternatively, you can use the T attribute
# transposed_matrix = original_matrix.T

print("Original Matrix:")
print(original_matrix)
print("\nTransposed Matrix:")
print(transposed_matrix)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transposed Matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [6]:
def transpose_matrix(matrix):
    # Get the number of rows and columns
    rows = len(matrix)
    cols = len(matrix[0])

    # Initialize a new matrix with swapped rows and columns
    transposed_matrix = [[0] * rows for _ in range(cols)]

    # Fill in the transposed matrix
    for i in range(rows):
        for j in range(cols):
            transposed_matrix[i][j] = matrix[j][i]

    return transposed_matrix

# Example usage:
original_matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

transposed_matrix = transpose_matrix(original_matrix)

print("Original Matrix:")
for row in original_matrix:
    print(row)

print("\nTransposed Matrix:")
for row in transposed_matrix:
    print(row)


Original Matrix:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]

Transposed Matrix:
[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


In [5]:
def in_place_transpose(matrix):
    # Get the number of rows and columns
    rows = len(matrix)
    cols = len(matrix[0])

    for i in range(rows):
        for j in range(i + 1, cols):
            # Swap elements across the main diagonal
            matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]

# Example usage:
original_matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print("Original Matrix:")
for row in original_matrix:
    print(row)

in_place_transpose(original_matrix)

print("\nIn-Place Transposed Matrix:")
for row in original_matrix:
    print(row)


Original Matrix:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]

In-Place Transposed Matrix:
[1, 4, 7]
[2, 5, 8]
[3, 6, 9]
